version: '3.9'


services:
  redis:
    container_name: redis
    restart: always
    image: redis
    ports:
    - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend1:
    container_name: backend1
    build: .
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.stage

    depends_on:
      - redis
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  celery:
    build: .
    command: celery -A core worker --loglevel=info
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.stage
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend1
  
  celery-beat:
    build: .
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler

    volumes:
      - ./core:/app
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.stage

    depends_on:
      - redis

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - redis
      - backend1
volumes:
  static_volume:
  media_volume:
  postgres_data:
