# Generated by Django 3.2.22 on 2023-10-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('status', models.IntegerField(choices=[(1, 'در حال انجام'), (2, 'تمام شده')])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
